-- phpMyAdmin SQL Dump
-- version 5.1.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Apr 27, 2024 at 04:08 PM
-- Server version: 5.7.24
-- PHP Version: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rifugi`
--

-- --------------------------------------------------------

--
-- Table structure for table `recensioni`
--

CREATE TABLE `recensioni` (
  `ID_Recensione` int(11) NOT NULL,
  `Recensione` varchar(5000) NOT NULL,
  `Utente` int(11) DEFAULT NULL,
  `Rifugio` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `recensioni`
--

INSERT INTO `recensioni` (`ID_Recensione`, `Recensione`, `Utente`, `Rifugio`) VALUES
(7, 'esempio 2', 2, 'R.A.CO'),
(8, 'bellissimo percorso', 1, 'R.A.CO');

-- --------------------------------------------------------

--
-- Table structure for table `rifugi`
--

CREATE TABLE `rifugi` (
  `IDRifugio` varchar(10) NOT NULL,
  `NomeRifugio` varchar(50) NOT NULL,
  `Provincia` varchar(20) NOT NULL,
  `Immagine` varchar(100) NOT NULL,
  `Descrizione` varchar(10000) NOT NULL,
  `Mappa` varchar(1000) NOT NULL,
  `Difficolta` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `rifugi`
--

INSERT INTO `rifugi` (`IDRifugio`, `NomeRifugio`, `Provincia`, `Immagine`, `Descrizione`, `Mappa`, `Difficolta`) VALUES
('B.M.V', 'Bivacco Molteni Valsecchi', 'Sondrio', 'rifugio_sondrio_img/Bivacco_Molteni-Valsecchi.jpg', 'Il bivacco Molteni-Valsecchi, è un bivacco situato nella valle del Ferro, nel comune di Val Masino.<br>\n                    Il bivacco è posto a 2.515 m s.l.m. in alta valle del Ferro, diramazione della Val Masino, \n                    e consiste in una struttura metallica che permette il pernottamento a 9 persone.<br>\n                    Si può arrivare al bivacco partendo dalla località San Martino Valmasino risalendo la Valle del Ferro in circa quattro ore e mezzo.<br>', 'https://www.google.it/maps/place/Bivacco+Molteni+Valsecchi/@46.2754479,9.6232178,17z/data=!3m1!4b1!4m5!3m4!1s0x47847bb060b74a5f:0x1d50e329568ba0e5!8m2!3d46.2754479!4d9.6254065?hl=it&authuser=0', 'intermedi'),
('C.MA', 'Capanna Mara', 'Lecco_Como', 'rifugo_lecco-como_img/Capanna_Mara-Alpe _del_Vicere.jpg', 'La Capanna Mara a 1125 metri, è situata tra i monti Bolettone e Palanzone, \r\n                    e precisamente poco sotto il valico che mette in comunicazione la val Bova e la val di Gaggia. <br>\r\n                    La via di salita più percorsa è quella che parte dall\'alpe del Viceré, sopra Erba.<br>', 'https://www.google.it/maps/place/Capanna+Mara/@45.8440429,9.1925229,17z/data=!3m1!4b1!4m8!3m7!1s0x4784200c050dcc69:0xf046197115eafe40!5m2!4m1!1i2!8m2!3d45.8440429!4d9.1947116?hl=it&authuser=0', 'semplici'),
('R.A.CO', 'Rifugio Alpe Corte', 'Bergamo', 'rifugi_bergamo_img/Alpe_Corte.jpg', 'Il rifugio (a quota 1410 m), facilmente accessibile dal paese di Valcanale, è immerso in una splendida pineta al cospetto di severissime pareti dolomitiche \r\n                    in un ambiente dei più suggestivi. Oltre ad essere la prima tappa del Sentiero delle Orobie Orientali, \r\n                    il rifugio è anche preziosa base d\'appoggio per raggiungere la zona del lago Branchino o per interessanti itinerari scialpinistici. <br>\r\n                    Dal 2007 i lavori di ristrutturazione e riqualificazione lo hanno reso agibile anche a persone \"diversamente abili\". <br>\r\n                    La configurazione delle camere, tutte con servizi, lo rendono ideale anche per famiglie con bimbi che gradiscono un po\' di privacy. <br>', 'https://www.google.it/maps/place/Rifugio+Alpe+Corte/@45.9577927,9.8217834,17z/data=!3m1!4b1!4m8!3m7!1s0x4783ef592a4b9b4b:0xcb982c6859ed615a!5m2!4m1!1i2!8m2!3d45.9577526!4d9.8239623?hl=it&authuser=0', 'semplici'),
('R.A.CU', 'Rifugio Antonio Curò', 'Bergamo', 'rifugi_bergamo_img/Curo.jpg', 'La conca del Barbellino è senza dubbio l\'area escursionisticamente più interessante di tutte le Alpi Orobie, \r\n                    per la presenza di tutta una serie di bellissime e non troppo impegnative vette, a quote che spesso sfiorano i 3000 m.<br>\r\n                    La zona fa parte della riserva naturale Belviso-Barbellino e pertanto la fauna alpina pregiata, specialmente nelle conche più appartate, è molto abbondante.\r\n                    Il rifugio Curò (1915 m) è conosciuto dagli appassionati anche per l\'immediata vicinanza delle famose Cascate del Serio che, \r\n                    con un triplice salto di oltre 315 metri, sono le più alte d\'Italia e le seconde d\'Europa.', 'https://www.google.it/maps/place/Rifugio+Antonio+Cur%C3%B2/@46.0617008,10.0460362,17z/data=!4m8!3m7!1s0x4783eaa7a78491b1:0x8cfbe497a4cf994!5m2!4m1!1i2!8m2!3d46.0618477!4d10.0477562?hl=it&authuser=0', 'intermedi'),
('R.AZ', 'Rifugio Azzoni', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_Azzoni.jpg', 'Il Resegone, montagna simbolo della città di Lecco sulla cui vetta si trova il rifugio, \r\n                    è una cima isolata di 1875 mt, con un panorama mozzafiato che spazia su tutto l’arco alpino e sugli Appennini. <br>\r\n                    Sono presenti una decina di sentieri di accesso dai vari versanti, a cui si aggiungono 7 vie ferrate di tutte le difficoltà.<br>', 'https://www.google.it/maps/place/Resegone/@45.8583321,9.4601342,15z/data=!3m1!4b1!4m5!3m4!1s0x478403b3ca97bbb9:0xbd26444861952e3d!8m2!3d45.858333!4d9.468889?hl=it&authuser=0', 'semplici'),
('R.B', 'Rifugio Begnigni', 'Bergamo', 'rifugi_bergamo_img/Benigni.jpg', 'Il Rifugio Benigni, di proprietà della Sezione CAI Alta Valle Brembana, di gradevole aspetto e di piccole dimensioni, \r\n                    è situato (a quota 2222 m) sulla testata della Valle di Salmurano, a breve distanza  dal Lago Piazzotti.<br>\r\n                    La costruzione del rifugio inizió nel 1982, grazie al lavoro di numerosi soci dell\'allora Sottosezione CAI  \r\n                    Alta Valle Brembana e al contributo della famiglia Benigni, la quale intese così onorare la memoria del loro caro Cesare, \r\n                    scomparso nel 1981 sul Pizzo del Diavolo di Tenda. Il Rifugio Benigni venne inaugurato il 26 Agosto del 1984, \r\n                    in un\'incantevole giornata di sole, alla presenza di numerosi escursionisti giunti da più parti. <br>\r\n                    Alcuni anni dopo venne aggiunto un piccolo locale invernale con otto posti letto, e nel 2007 ampliato significativamente con una nuova sala ristorante, \r\n                    una cucina più spaziosa, due servizi igienici e una saletta per il bar.', 'https://www.google.it/maps/place/Rifugio+C.+Benigni/@46.0214013,9.5596606,17z/data=!3m1!4b1!4m8!3m7!1s0x478408eff0007683:0x30d5fe4fd3bb4b1!5m2!4m1!1i2!8m2!3d46.021388!4d9.5618282?hl=it&authuser=0', 'difficile'),
('R.B.AD', 'Rifugio Baita Adame', 'Brescia', 'rifugi_brescia_img/Rifugio_Baita_Adame.jpg', 'Il rifugio è nelle Alpi Retiche Gruppo dell’Adamello/Levade immerso nella splendida Valle Adamè a 2.150 m. <br>\r\n                    Posizionato a metà valle sul sentiero n°1 del Parco dell’Adamello, \r\n                    il Rifugio Baita Adamè è la meta ideale per coloro che intendono ammirare la vastità della valle glaciale \r\n                    più grande del gruppo dell’Adamello.<br>', 'https://www.google.it/maps/place/Rifugio+Baita+Adam%C3%A8/@46.1027221,10.5169849,17z/data=!3m1!4b1!4m5!3m4!1s0x47824c74dc96eb39:0x1b8e9a249da10b14!8m2!3d46.1027221!4d10.5191736?hl=it&authuser=0', 'semplici'),
('R.BA', 'Rifugio Baitone', 'Brescia', 'rifugi_brescia_img/Rifugio_Baitone.jpg', 'Il Rifugio Baitone è un rifugio già di proprietà di Enel ,ceduto al Comune di Sonico che lo ha ristrutturato. \r\n                    Posizionato nel cuore del Parco dell’Adamello dove le caratteristiche naturali realizzano l’area più vocata ad ospitare \r\n                    lo stambecco regale ungulato tornato di recente a frequentare le valli Adamelline.<br>', 'https://www.google.it/maps/place/Rifugio+Baitone/@46.1408221,10.4292792,17z/data=!3m1!4b1!4m5!3m4!1s0x4783b37c7f90425b:0x884694af5f960354!8m2!3d46.1408221!4d10.4314679?hl=it&authuser=0', 'intermedi'),
('R.BE', 'Rifugio Bertacchi', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Bertacchi.jpg', 'Sorge in posizione panoramica presso il lago d’Emet, in alta Val San Giacomo, a quota 2175m. <br>\r\n                    È collocato nei pressi del lago Emet e poco sotto il passo di Niemet.<br>\r\n                    È dedicato al poeta della Valchiavenna, Giovanni Bertacchi.<br>', 'https://www.google.it/maps/place/Rifugio+Giovanni+Bertacchi/@46.4690738,9.3765652,17z/data=!3m1!4b1!4m5!3m4!1s0x4784f50f7983049f:0xd15d98478991a073!8m2!3d46.4690738!4d9.3787539?hl=it&authuser=0', 'difficile'),
('R.CA', 'Rifugio Calvi', 'Bergamo', 'rifugi_bergamo_img/Calvi.jpg', 'Il rifugio Fratelli Calvi si trova nel centro di una delle conche più belle dell\'arco Orobico, \r\n                        a cui fanno capo tutte le maggiori elevazioni della Val Brembana. \r\n                        Tra queste spicca senz\'altro la cuspide del Diavolo di Tenda, che costituisce sicuramente la montagna più rappresentativa della zona. <br> \r\n                        Il rifugio è un\'ottima base per salite escursionistiche e alpinistiche, Facili e anche molto Difficili, nonchè per svariati itinerari di Scialpinismo. \r\n                        Presso questa conca, ogni anno viene inoltre organizzata dallo SCI-CAI Bergamo la gara di scialpinismo a coppie \"Trofeo Parravicini\". <br>\r\n                        E’ il naturale punto d’appoggio per le ascensioni al Pizzo del Diavolo, al M. Grabiasca, al M. Madonnino e al M. Cabianca. Le ultime tre cime, \r\n                        inoltre, rappresentano i vertici del percorso del celebre “Trofeo Parravicini”: la gara sci-alpinistica internazionale a coppie organizzata \r\n                        dalla sezione CAI di Bergamo che, fin dalla sua istituzione, ha fissato la propria base logistica in questo Rifugio.', 'https://www.google.it/maps/place/Rifugio+Fratelli+Calvi/@46.0235252,9.8748903,17z/data=!3m1!4b1!4m8!3m7!1s0x4783edc4fbf9d665:0xa864ff2bd3f3e819!5m2!4m1!1i2!8m2!3d46.0235252!4d9.877079?hl=it&authuser=0', 'intermedi'),
('R.CAZ', 'Rifugio Cazzaniga Merlini', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_Cazzaniga-Merlini.jpg', 'Il rifugio è situato a 1900mt ai Piani di Artavaggio, Valsassina. <br>\r\n                    È di proprietà dell\' ANA di Lecco e si trova su un evidente sperone roccioso, quale fosse il nido di un\'acquila. <br>\r\n                    La sua struttura ottagonale permette di avere una visuale a 360° sul panorama circostante \r\n                    dalle Orobie all’Appennino fino alle Alpi con il versante est delle Grigne in primo piano. <br>\r\n                    Dalle vicinanze si possono ammirare anche le Alpi Retiche ed il Pizzo dei 3 Signori. <br>', 'https://www.google.it/maps/place/Rifugio+Cazzaniga+Merlini/@45.9445085,9.5347272,17z/data=!3m1!4b1!4m5!3m4!1s0x478405ad13bdc5cf:0x65a7ebfc0649b98a!8m2!3d45.9445085!4d9.5369159?hl=it&authuser=0', 'intermedi'),
('R.CE', 'Rifugio Cernello', 'Bergamo', 'rifugi_bergamo_img/Cernello.jpg', 'Come spesso succede quando si raggiunge un \"mini-rifugio\" (baita sociale del CAI Alzano L.) come questo (a quota 1956 m), \r\n                    quando si sale alla baita Cernello pare di trovarsi d\'un tratto in un luogo estremamente selvaggio e sconosciuto: così, \r\n                    passare una notte in autogestione in questo luogo, rappresenta un\'esperienza senz\'altro unica e raccomandabile. <br>\r\n                    In zona c\'è la possibilità di effettuare un bellissimo giro ad anello tra i numerosi bacini, artificiali e non, \r\n                    che costellano l\'altopiano roccioso alle spalle di Valgoglio. <br>\r\n                    I loro intensi colori sono particolarmente suggestivi perchè contrastano nettamente le tonalità calde delle pareti circostanti. <br>', 'https://www.google.it/maps/place/Baita+Cernello/@46.0020657,9.8847897,17z/data=!3m1!4b1!4m8!3m7!1s0x4783ee87ce10009b:0x84903457c8ddca25!5m2!4m1!1i2!8m2!3d46.0020657!4d9.8869784?hl=it&authuser=0', 'intermedi'),
('R.G.CA', 'Rifugio Gianni Casati', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Casati.jpg', 'Il rifugio Gianni Casati è un rifugio alpino situato nel comune di Valfurva, in Valtellina, a 3269m. <br>\r\n                    Si trova al passo del Cevedale, al confine tra Lombardia e Trentino-Alto Adige.  <br>\r\n                    È un punto di partenza per ascensioni alpinistiche al monte Cevedale (3.769 m) e Gran Zebrù (3.851 m).<br>', 'https://www.google.it/maps/place/Rifugio+Casati+al+Cevedale+mt+3269+-+CAI+Milano/@46.463158,10.6003003,17z/data=!3m1!4b1!4m8!3m7!1s0x4783016786588143:0xc0afb8a88f5d1295!5m2!4m1!1i2!8m2!3d46.463158!4d10.602489?hl=it&authuser=0', 'semplici'),
('R.GA', 'Rifugio Garibaldi', 'Brescia', 'rifugi_brescia_img/Rifugio_Garibaldi.jpg', 'Il Rifugio Giuseppe Garibaldi si trova sulla sponda del Lago Venerocolo alla base della imponente pare­te nord dell’Adamello, \r\n                    in uno scenario di vette di in­comparabile bellezza. <br>\r\n                    E’ il punto di arrivo dell’Alta Via dell’Adamello per chi la percorre nel senso da sud a nord.<br>', 'https://www.google.it/maps/place/Rifugio+Garibaldi+C.A.I./@46.1794678,10.4928325,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b1b4d2e9a7db:0xffc92204c653809!5m2!4m1!1i2!8m2!3d46.1794678!4d10.4950212?hl=it&authuser=0', 'intermedi'),
('R.GN', 'Rifugio Gnutti', 'Brescia', 'rifugi_brescia_img/Rifugio_Gnutti.jpg', 'E’ raggiungibile in circa 2 ore di cammino partendo dalla località Ponte del Guat,10 km oltre l’abitato di Sonico. <br>\r\n                    Questa escursione si sviluppa lungo il sentiero 23 passando per le famose “Scale Del Milller”, \r\n                    accessibili a tutti senza grosse difficoltà, in uno scenario di incantevole e selvaggia bellezza. <br>\r\n                    Il rifugio è conosciuto per essere la base di partenza per l’ascensione alla Vetta Adamello.<br>', 'https://www.google.it/maps/place/Rifugio+Serafino+Gnutti/@46.1312785,10.4517058,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b171e7f4c621:0x2f6172564f286dfc!5m2!4m1!1i2!8m2!3d46.1312785!4d10.4538945?hl=it&authuser=0', 'semplici'),
('R.L.G', 'Rifugio Laghi Gemelli', 'Bergamo', 'rifugi_bergamo_img/Laghi_Gemelli.jpg', 'Il rifugio (quota 1968 m) si trova sulle rive dei famosi laghi Gemelli, un invaso di oltre 5.000.000 di metri cubi di acqua. \r\n                    La zona è conosciuta col nome di \"altopiano dei laghi\" per la presenza di ben una decina di laghi artificiali a poca distanza tra loro. <br>\r\n                    La vetta più significativa della zona è sicuramente il pizzo del Becco (2507 m), \r\n                    che domina il paesaggio con i suoi ripidissimi dirupi meridionale e l\'ancor più selvaggia parete settentrionale. \r\n                    Su entrambi i versanti sono state tracciati svariati itinerari di arrampicata sempre su roccia eccellente (verrucano lombardo). <br>\r\n                    Il rifugio offre agli escursionisti un servizio di bar, ristorante e pernottamento in un ambiente giovanile, \r\n                    dove troverete un’ottima accoglienza e una cucina curata e attenta ai piatti tipici della tradizione locale accompagnati da una selezione di vini della zona. <br>', 'https://www.google.it/maps/place/Laghi+Gemelli/@45.9873047,9.8035188,16z/data=!3m1!4b1!4m5!3m4!1s0x4783f1c8259a41b3:0x2a2e345a97722a8b!8m2!3d45.9849029!4d9.8072926?hl=it&authuser=0', 'intermedi'),
('R.LI', 'Rifugio Lissone', 'Brescia', 'rifugi_brescia_img/Rifugio_Lissone.jpg', 'Il Rifugio Città di Lissone situato nel comune di Saviore dell’Adamello , in Val Camonica, a 2.020 m. <br>\r\n                    Accanto al rifugio è presente un invaso artificiale che raccoglie le acque del torrente Poia, \r\n                    mentre una teleferica permette il trasporto di carichi dalla Malga Lincino al rifugio.<br>', 'https://www.google.it/maps/place/Rifugio+Citt%C3%A0+di+Lissone/@46.0832785,10.4945368,17z/data=!3m1!4b1!4m8!3m7!1s0x47824ba64d7cfab5:0xaf9f4db3a0a69ca2!5m2!4m1!1i2!8m2!3d46.0832785!4d10.4967255?hl=it&authuser=0', 'difficile'),
('R.M.M.C', 'Rifugio Mario Marinelli al Coca', 'Bergamo', 'rifugi_bergamo_img/Coca.jpg', 'Il rifugio Mario Merelli al Coca è stato intitolato all\'alpinista scomparso su queste montagne nel gennaio del 2012. \r\n                    Si trova a quota 1891 m in uno degli angoli più suggestivi e selvaggi delle Orobie: siamo vicino alla località nota come \"Conca dei Giganti\", \r\n                    dove svettano tutte le maggiori elevazioni del gruppo. Numerosi itinerari di arrampicata su roccia e lungo canaloni e couloir. \r\n                    Dal passo di Coca è possibile raggiungere il ghiacciaio del Lupo e il non distante bivacco Corti.\r\n                    Costruito nel 1919 su progetto dell\'ingegnere Luigi Albani, di proprietà del Club Alpino Italiano di Bergamo, \r\n                    venne dedicato al ricordo degli undici soci CAI morti durante la Prima Guerra. E’ posto  alla base dei giganti orobici: \r\n                    il Pizzo Coca (3050 m) e il Pizzo Redorta (3037 m), nonché alle altre cime che coronano la Val Bondione. L’ampliamento avvenuto nel 1957, \r\n                    su progetto dell\'architetto Maria Luisa Berti Angelini, ha dotato il rifugio di 60 posti letto e corrente elettrica.', 'https://www.google.it/maps/place/Rifugio+Merelli+al+Coca/@46.0539106,10.0064534,15.23z/data=!4m8!3m7!1s0x4783eae6479ababd:0xe7325dc7e2d7ddda!5m2!4m1!1i2!8m2!3d46.0547085!4d10.0098087?hl=it&authuser=0', 'difficile'),
('R.O', 'Rifugio Olmo', 'Bergamo', 'rifugi_bergamo_img/Olmo.jpg', 'Il rifugio dedicato alla memoria di Rino Olmo fu inaugurato il 29 settembre del 1991, \r\n                    in seguito alla ristrutturazione della Baita di Olone, con notevole impegno lavorativo ed economico da parte dei soci della Sezione CAI di Clusone. <br>\r\n                    E\' ubicato a 1819 metri di altezza con una posizione di tutto rispetto, dolcemente adagiato in una conca poco sotto il passo Olone. <br>\r\n                    Il Rifugio Olmo gode dell\'invidiabile vista sul dolomitico versante sud della Regina delle Orobie: la Presolana. <br>', 'https://www.google.it/maps/place/Rifugio+Rino+Olmo/@45.9481811,10.0355672,17z/data=!3m1!4b1!4m8!3m7!1s0x4783dd243fdfcd17:0x4032d024f9cb1005!5m2!4m1!1i2!8m2!3d45.9481811!4d10.0377559?hl=it&authuser=0', 'intermedi'),
('R.R', 'Rifugio Resegone', 'Bergamo', 'rifugi_bergamo_img/Resegone.jpg', 'L\'ultimo dei rifugi CAI bergamaschi è stato inaugurato il 15 settembre 2013. \r\n                    Realizzato dalla Sottosezione CAI Valle Imagna a quota 1265 m lungo il sentiero che da Brumano sale al Resegone è la sosta \r\n                    ideale per chi vorrà compiere il periplo del Resegone, salire alle creste, o vorrà semplicemente effettuare una breve escursione.<br>\r\n                    Escursioni partendo dal rifugio: <br>\r\n                    al Rifugio Azzoni (m.1860) in ore 1.30;<br>\r\n                    alla Vetta del Resegone (m.1875) in ore 1.35.<br>', 'https://www.google.it/maps/place/Rifugio+Resegone/@45.8560958,9.4869938,17z/data=!3m1!4b1!4m8!3m7!1s0x478403cdf0adb601:0x75999390dd46c6cc!5m2!4m1!1i2!8m2!3d45.8560958!4d9.4891825?hl=it&authuser=0', 'semplici'),
('R.SEV', 'Rifugio SEV - Corni di Canzo', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_SEV-Corni_di_Canzo.jpg', 'Nella zona di Pianezzo, a fianco dei Corni di Canzo, meta abituale degli escursionisti del territorio lecchese, \r\n                    è situato il rifugio della Società Escursionisti Valmadreresi; \r\n                    iniziato nel 1957 e i cui lavori terminarono nel 1964 grazie al contributo di numerosi soci volontari. <br>', 'https://www.google.it/maps/place/Rifugio+S.E.V./@45.8642842,9.3251813,17z/data=!3m1!4b1!4m8!3m7!1s0x47841dcd0b6085a9:0x5f8740d1fed121d7!5m2!4m1!1i2!8m2!3d45.8642842!4d9.32737?hl=it&authuser=0', 'difficile'),
('R.T', 'Rifugio Tagliaferri', 'Bergamo', 'rifugi_bergamo_img/Tagliaferri.jpg', 'Il rifugio è posto quale tappa intermedia all\'itinerario naturalistico Antonio Curò trovandosi esattamente a metà strada tra il rifugio Curò e il passo del Vivione. <br>\r\n                    L\'ambiente è molto interessante sia per la fauna e la flora (la zona è tutelata dalla riserva faunistico venatoria Valbelviso – Barbellino), \r\n                    sia per i numerosi specchi d\'acqua sparsi lungo tutti i versanti delle montagne circostanti.\r\n                    Locale invernale con apparato SOS che permette di effettuare chiamate dirette al CNSAS e al 118. <br>\r\n                    Venne inaugurato il 22 settembre 1985 grazie alla volontà degli scalvini con il contributo economico della comunità  Montana e del CAI di Bergamo. \r\n                    É intitolato al primo presidente della Sottosezione Valle di Scalve, Nani Tagliaferri, tragicamente scomparso nel 1981 tra i ghiacci delle Ande Peruviane, \r\n                    insieme agli amici Italo Maj e Livio Piantoni. <br>\r\n                    L’anno seguente subì un devastante incendio che lo distrusse quasi completamente ma la tenacia dei soci permise l’immediata ricostruzione. \r\n                    Situato a 2328 m s.l.m. è il rifugio più alto delle Orobie. <br>', 'https://www.google.it/maps/place/Rifugio+Nani+Tagliaferri/@46.05537,10.1123954,17z/data=!3m1!4b1!4m8!3m7!1s0x4783c6c0d7b3ae1b:0x1368d4eb995adabd!5m2!4m1!1i2!8m2!3d46.05537!4d10.1145841?hl=it&authuser=0', 'difficile'),
('R.TO', 'Rifugio Tonolini', 'Brescia', 'rifugi_brescia_img/Rifugio_Tonolini.jpg', 'Il rifugio Franco Tonolini si trova nella Conca del Baitone, nel Parco dell Adamello, nei pressi del lago Rotondo. <br>\r\n                    Circondato da ben otto bellissimi laghetti alpini e in posizione ideale per ottime escursioni .<br>', 'https://www.google.it/maps/place/Rifugio+Franco+Tonolini/@46.1504498,10.4381329,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b31ebc2d871b:0xfcdda27227754318!5m2!4m1!1i2!8m2!3d46.1504498!4d10.4403216?hl=it&authuser=0', 'semplici'),
('R.V.A', 'Rifugio Volta A.', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Volta.jpg', 'Il Rifugio Volta è situato al centro della testata della Val dei Ratti.\r\n                    Gli fanno da corona le cime che separano questa valle dalla Val Codera e dalla Val Masino. <br>\r\n                    Partendo da sinistra (ovest) vediamo: il Sasso Manduino (m. 2888), \r\n                    la Punta Magnaghi (m. 2871), le Cime di Gaiazzo (m. 2597 e m. 2920), la Bocchetta di Spassato (m. 2820), \r\n                    il Pizzo Ligoncio (m. 3032), il Pizzo della Vedretta (m. 2907), la Cima del Calvo (m. 2967), il Passo di Primalpia (m. 2476),<br> \r\n                    il M. Spluga o Cima di Dosenigo (m. 2845).<br>', 'https://www.google.it/maps/place/Capanna+Volta/@46.2242886,9.5386642,17z/data=!3m1!4b1!4m5!3m4!1s0x478471d002a40cbd:0x3e58797ce7eb74c7!8m2!3d46.2242886!4d9.5408529?hl=it&authuser=0', 'intermedi');

-- --------------------------------------------------------

--
-- Table structure for table `rifugi_tmp`
--

CREATE TABLE `rifugi_tmp` (
  `IDRifugio` varchar(10) NOT NULL,
  `NomeRifugio` varchar(50) NOT NULL,
  `Provincia` varchar(20) NOT NULL,
  `Immagine` varchar(100) NOT NULL,
  `Descrizione` varchar(10000) NOT NULL,
  `Mappa` varchar(1000) NOT NULL,
  `Difficolta` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `rifugi_tmp`
--

INSERT INTO `rifugi_tmp` (`IDRifugio`, `NomeRifugio`, `Provincia`, `Immagine`, `Descrizione`, `Mappa`, `Difficolta`) VALUES
('B.M.V', 'Bivacco Molteni Valsecchi', 'Sondrio', 'rifugio_sondrio_img/Bivacco_Molteni-Valsecchi.jpg', 'Il bivacco Molteni-Valsecchi, è un bivacco situato nella valle del Ferro, nel comune di Val Masino.<br>\n                    Il bivacco è posto a 2.515 m s.l.m. in alta valle del Ferro, diramazione della Val Masino, \n                    e consiste in una struttura metallica che permette il pernottamento a 9 persone.<br>\n                    Si può arrivare al bivacco partendo dalla località San Martino Valmasino risalendo la Valle del Ferro in circa quattro ore e mezzo.<br>', 'https://www.google.it/maps/place/Bivacco+Molteni+Valsecchi/@46.2754479,9.6232178,17z/data=!3m1!4b1!4m5!3m4!1s0x47847bb060b74a5f:0x1d50e329568ba0e5!8m2!3d46.2754479!4d9.6254065?hl=it&authuser=0', 'intermedi'),
('C.MA', 'Capanna Mara', 'Lecco_Como', 'rifugo_lecco-como_img/Capanna_Mara-Alpe _del_Vicere.jpg', 'La Capanna Mara a 1125 metri, è situata tra i monti Bolettone e Palanzone, \r\n                    e precisamente poco sotto il valico che mette in comunicazione la val Bova e la val di Gaggia. <br>\r\n                    La via di salita più percorsa è quella che parte dall\'alpe del Viceré, sopra Erba.<br>', 'https://www.google.it/maps/place/Capanna+Mara/@45.8440429,9.1925229,17z/data=!3m1!4b1!4m8!3m7!1s0x4784200c050dcc69:0xf046197115eafe40!5m2!4m1!1i2!8m2!3d45.8440429!4d9.1947116?hl=it&authuser=0', 'semplici'),
('R.A.CO', 'Rifugio Alpe Corte', 'Bergamo', 'rifugi_bergamo_img/Alpe_Corte.jpg', 'Il rifugio (a quota 1410 m), facilmente accessibile dal paese di Valcanale, è immerso in una splendida pineta al cospetto di severissime pareti dolomitiche \r\n                    in un ambiente dei più suggestivi. Oltre ad essere la prima tappa del Sentiero delle Orobie Orientali, \r\n                    il rifugio è anche preziosa base d\'appoggio per raggiungere la zona del lago Branchino o per interessanti itinerari scialpinistici. <br>\r\n                    Dal 2007 i lavori di ristrutturazione e riqualificazione lo hanno reso agibile anche a persone \"diversamente abili\". <br>\r\n                    La configurazione delle camere, tutte con servizi, lo rendono ideale anche per famiglie con bimbi che gradiscono un po\' di privacy. <br>', 'https://www.google.it/maps/place/Rifugio+Alpe+Corte/@45.9577927,9.8217834,17z/data=!3m1!4b1!4m8!3m7!1s0x4783ef592a4b9b4b:0xcb982c6859ed615a!5m2!4m1!1i2!8m2!3d45.9577526!4d9.8239623?hl=it&authuser=0', 'semplici'),
('R.A.CU', 'Rifugio Antonio Curò', 'Bergamo', 'rifugi_bergamo_img/Curo.jpg', 'La conca del Barbellino è senza dubbio l\'area escursionisticamente più interessante di tutte le Alpi Orobie, \r\n                    per la presenza di tutta una serie di bellissime e non troppo impegnative vette, a quote che spesso sfiorano i 3000 m.<br>\r\n                    La zona fa parte della riserva naturale Belviso-Barbellino e pertanto la fauna alpina pregiata, specialmente nelle conche più appartate, è molto abbondante.\r\n                    Il rifugio Curò (1915 m) è conosciuto dagli appassionati anche per l\'immediata vicinanza delle famose Cascate del Serio che, \r\n                    con un triplice salto di oltre 315 metri, sono le più alte d\'Italia e le seconde d\'Europa.', 'https://www.google.it/maps/place/Rifugio+Antonio+Cur%C3%B2/@46.0617008,10.0460362,17z/data=!4m8!3m7!1s0x4783eaa7a78491b1:0x8cfbe497a4cf994!5m2!4m1!1i2!8m2!3d46.0618477!4d10.0477562?hl=it&authuser=0', 'intermedi'),
('R.AZ', 'Rifugio Azzoni', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_Azzoni.jpg', 'Il Resegone, montagna simbolo della città di Lecco sulla cui vetta si trova il rifugio, \r\n                    è una cima isolata di 1875 mt, con un panorama mozzafiato che spazia su tutto l’arco alpino e sugli Appennini. <br>\r\n                    Sono presenti una decina di sentieri di accesso dai vari versanti, a cui si aggiungono 7 vie ferrate di tutte le difficoltà.<br>', 'https://www.google.it/maps/place/Resegone/@45.8583321,9.4601342,15z/data=!3m1!4b1!4m5!3m4!1s0x478403b3ca97bbb9:0xbd26444861952e3d!8m2!3d45.858333!4d9.468889?hl=it&authuser=0', 'semplici'),
('R.B', 'Rifugio Begnigni', 'Bergamo', 'rifugi_bergamo_img/Benigni.jpg', 'Il Rifugio Benigni, di proprietà della Sezione CAI Alta Valle Brembana, di gradevole aspetto e di piccole dimensioni, \r\n                    è situato (a quota 2222 m) sulla testata della Valle di Salmurano, a breve distanza  dal Lago Piazzotti.<br>\r\n                    La costruzione del rifugio inizió nel 1982, grazie al lavoro di numerosi soci dell\'allora Sottosezione CAI  \r\n                    Alta Valle Brembana e al contributo della famiglia Benigni, la quale intese così onorare la memoria del loro caro Cesare, \r\n                    scomparso nel 1981 sul Pizzo del Diavolo di Tenda. Il Rifugio Benigni venne inaugurato il 26 Agosto del 1984, \r\n                    in un\'incantevole giornata di sole, alla presenza di numerosi escursionisti giunti da più parti. <br>\r\n                    Alcuni anni dopo venne aggiunto un piccolo locale invernale con otto posti letto, e nel 2007 ampliato significativamente con una nuova sala ristorante, \r\n                    una cucina più spaziosa, due servizi igienici e una saletta per il bar.', 'https://www.google.it/maps/place/Rifugio+C.+Benigni/@46.0214013,9.5596606,17z/data=!3m1!4b1!4m8!3m7!1s0x478408eff0007683:0x30d5fe4fd3bb4b1!5m2!4m1!1i2!8m2!3d46.021388!4d9.5618282?hl=it&authuser=0', 'difficile'),
('R.B.AD', 'Rifugio Baita Adame', 'Brescia', 'rifugi_brescia_img/Rifugio_Baita_Adame.jpg', 'Il rifugio è nelle Alpi Retiche Gruppo dell’Adamello/Levade immerso nella splendida Valle Adamè a 2.150 m. <br>\r\n                    Posizionato a metà valle sul sentiero n°1 del Parco dell’Adamello, \r\n                    il Rifugio Baita Adamè è la meta ideale per coloro che intendono ammirare la vastità della valle glaciale \r\n                    più grande del gruppo dell’Adamello.<br>', 'https://www.google.it/maps/place/Rifugio+Baita+Adam%C3%A8/@46.1027221,10.5169849,17z/data=!3m1!4b1!4m5!3m4!1s0x47824c74dc96eb39:0x1b8e9a249da10b14!8m2!3d46.1027221!4d10.5191736?hl=it&authuser=0', 'semplici'),
('R.BA', 'Rifugio Baitone', 'Brescia', 'rifugi_brescia_img/Rifugio_Baitone.jpg', 'Il Rifugio Baitone è un rifugio già di proprietà di Enel ,ceduto al Comune di Sonico che lo ha ristrutturato. \r\n                    Posizionato nel cuore del Parco dell’Adamello dove le caratteristiche naturali realizzano l’area più vocata ad ospitare \r\n                    lo stambecco regale ungulato tornato di recente a frequentare le valli Adamelline.<br>', 'https://www.google.it/maps/place/Rifugio+Baitone/@46.1408221,10.4292792,17z/data=!3m1!4b1!4m5!3m4!1s0x4783b37c7f90425b:0x884694af5f960354!8m2!3d46.1408221!4d10.4314679?hl=it&authuser=0', 'intermedi'),
('R.BE', 'Rifugio Bertacchi', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Bertacchi.jpg', 'Sorge in posizione panoramica presso il lago d’Emet, in alta Val San Giacomo, a quota 2175m. <br>\r\n                    È collocato nei pressi del lago Emet e poco sotto il passo di Niemet.<br>\r\n                    È dedicato al poeta della Valchiavenna, Giovanni Bertacchi.<br>', 'https://www.google.it/maps/place/Rifugio+Giovanni+Bertacchi/@46.4690738,9.3765652,17z/data=!3m1!4b1!4m5!3m4!1s0x4784f50f7983049f:0xd15d98478991a073!8m2!3d46.4690738!4d9.3787539?hl=it&authuser=0', 'difficile'),
('R.CA', 'Rifugio Calvi', 'Bergamo', 'rifugi_bergamo_img/Calvi.jpg', 'Il rifugio Fratelli Calvi si trova nel centro di una delle conche più belle dell\'arco Orobico, \r\n                        a cui fanno capo tutte le maggiori elevazioni della Val Brembana. \r\n                        Tra queste spicca senz\'altro la cuspide del Diavolo di Tenda, che costituisce sicuramente la montagna più rappresentativa della zona. <br> \r\n                        Il rifugio è un\'ottima base per salite escursionistiche e alpinistiche, Facili e anche molto Difficili, nonchè per svariati itinerari di Scialpinismo. \r\n                        Presso questa conca, ogni anno viene inoltre organizzata dallo SCI-CAI Bergamo la gara di scialpinismo a coppie \"Trofeo Parravicini\". <br>\r\n                        E’ il naturale punto d’appoggio per le ascensioni al Pizzo del Diavolo, al M. Grabiasca, al M. Madonnino e al M. Cabianca. Le ultime tre cime, \r\n                        inoltre, rappresentano i vertici del percorso del celebre “Trofeo Parravicini”: la gara sci-alpinistica internazionale a coppie organizzata \r\n                        dalla sezione CAI di Bergamo che, fin dalla sua istituzione, ha fissato la propria base logistica in questo Rifugio.', 'https://www.google.it/maps/place/Rifugio+Fratelli+Calvi/@46.0235252,9.8748903,17z/data=!3m1!4b1!4m8!3m7!1s0x4783edc4fbf9d665:0xa864ff2bd3f3e819!5m2!4m1!1i2!8m2!3d46.0235252!4d9.877079?hl=it&authuser=0', 'intermedi'),
('R.CAZ', 'Rifugio Cazzaniga Merlini', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_Cazzaniga-Merlini.jpg', 'Il rifugio è situato a 1900mt ai Piani di Artavaggio, Valsassina. <br>\r\n                    È di proprietà dell\' ANA di Lecco e si trova su un evidente sperone roccioso, quale fosse il nido di un\'acquila. <br>\r\n                    La sua struttura ottagonale permette di avere una visuale a 360° sul panorama circostante \r\n                    dalle Orobie all’Appennino fino alle Alpi con il versante est delle Grigne in primo piano. <br>\r\n                    Dalle vicinanze si possono ammirare anche le Alpi Retiche ed il Pizzo dei 3 Signori. <br>', 'https://www.google.it/maps/place/Rifugio+Cazzaniga+Merlini/@45.9445085,9.5347272,17z/data=!3m1!4b1!4m5!3m4!1s0x478405ad13bdc5cf:0x65a7ebfc0649b98a!8m2!3d45.9445085!4d9.5369159?hl=it&authuser=0', 'intermedi'),
('R.CE', 'Rifugio Cernello', 'Bergamo', 'rifugi_bergamo_img/Cernello.jpg', 'Come spesso succede quando si raggiunge un \"mini-rifugio\" (baita sociale del CAI Alzano L.) come questo (a quota 1956 m), \r\n                    quando si sale alla baita Cernello pare di trovarsi d\'un tratto in un luogo estremamente selvaggio e sconosciuto: così, \r\n                    passare una notte in autogestione in questo luogo, rappresenta un\'esperienza senz\'altro unica e raccomandabile. <br>\r\n                    In zona c\'è la possibilità di effettuare un bellissimo giro ad anello tra i numerosi bacini, artificiali e non, \r\n                    che costellano l\'altopiano roccioso alle spalle di Valgoglio. <br>\r\n                    I loro intensi colori sono particolarmente suggestivi perchè contrastano nettamente le tonalità calde delle pareti circostanti. <br>', 'https://www.google.it/maps/place/Baita+Cernello/@46.0020657,9.8847897,17z/data=!3m1!4b1!4m8!3m7!1s0x4783ee87ce10009b:0x84903457c8ddca25!5m2!4m1!1i2!8m2!3d46.0020657!4d9.8869784?hl=it&authuser=0', 'intermedi'),
('R.G.CA', 'Rifugio Gianni Casati', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Casati.jpg', 'Il rifugio Gianni Casati è un rifugio alpino situato nel comune di Valfurva, in Valtellina, a 3269m. <br>\r\n                    Si trova al passo del Cevedale, al confine tra Lombardia e Trentino-Alto Adige.  <br>\r\n                    È un punto di partenza per ascensioni alpinistiche al monte Cevedale (3.769 m) e Gran Zebrù (3.851 m).<br>', 'https://www.google.it/maps/place/Rifugio+Casati+al+Cevedale+mt+3269+-+CAI+Milano/@46.463158,10.6003003,17z/data=!3m1!4b1!4m8!3m7!1s0x4783016786588143:0xc0afb8a88f5d1295!5m2!4m1!1i2!8m2!3d46.463158!4d10.602489?hl=it&authuser=0', 'semplici'),
('R.GA', 'Rifugio Garibaldi', 'Brescia', 'rifugi_brescia_img/Rifugio_Garibaldi.jpg', 'Il Rifugio Giuseppe Garibaldi si trova sulla sponda del Lago Venerocolo alla base della imponente pare­te nord dell’Adamello, \r\n                    in uno scenario di vette di in­comparabile bellezza. <br>\r\n                    E’ il punto di arrivo dell’Alta Via dell’Adamello per chi la percorre nel senso da sud a nord.<br>', 'https://www.google.it/maps/place/Rifugio+Garibaldi+C.A.I./@46.1794678,10.4928325,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b1b4d2e9a7db:0xffc92204c653809!5m2!4m1!1i2!8m2!3d46.1794678!4d10.4950212?hl=it&authuser=0', 'intermedi'),
('R.GN', 'Rifugio Gnutti', 'Brescia', 'rifugi_brescia_img/Rifugio_Gnutti.jpg', 'E’ raggiungibile in circa 2 ore di cammino partendo dalla località Ponte del Guat,10 km oltre l’abitato di Sonico. <br>\r\n                    Questa escursione si sviluppa lungo il sentiero 23 passando per le famose “Scale Del Milller”, \r\n                    accessibili a tutti senza grosse difficoltà, in uno scenario di incantevole e selvaggia bellezza. <br>\r\n                    Il rifugio è conosciuto per essere la base di partenza per l’ascensione alla Vetta Adamello.<br>', 'https://www.google.it/maps/place/Rifugio+Serafino+Gnutti/@46.1312785,10.4517058,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b171e7f4c621:0x2f6172564f286dfc!5m2!4m1!1i2!8m2!3d46.1312785!4d10.4538945?hl=it&authuser=0', 'semplici'),
('R.L.G', 'Rifugio Laghi Gemelli', 'Bergamo', 'rifugi_bergamo_img/Laghi_Gemelli.jpg', 'Il rifugio (quota 1968 m) si trova sulle rive dei famosi laghi Gemelli, un invaso di oltre 5.000.000 di metri cubi di acqua. \r\n                    La zona è conosciuta col nome di \"altopiano dei laghi\" per la presenza di ben una decina di laghi artificiali a poca distanza tra loro. <br>\r\n                    La vetta più significativa della zona è sicuramente il pizzo del Becco (2507 m), \r\n                    che domina il paesaggio con i suoi ripidissimi dirupi meridionale e l\'ancor più selvaggia parete settentrionale. \r\n                    Su entrambi i versanti sono state tracciati svariati itinerari di arrampicata sempre su roccia eccellente (verrucano lombardo). <br>\r\n                    Il rifugio offre agli escursionisti un servizio di bar, ristorante e pernottamento in un ambiente giovanile, \r\n                    dove troverete un’ottima accoglienza e una cucina curata e attenta ai piatti tipici della tradizione locale accompagnati da una selezione di vini della zona. <br>', 'https://www.google.it/maps/place/Laghi+Gemelli/@45.9873047,9.8035188,16z/data=!3m1!4b1!4m5!3m4!1s0x4783f1c8259a41b3:0x2a2e345a97722a8b!8m2!3d45.9849029!4d9.8072926?hl=it&authuser=0', 'intermedi'),
('R.LI', 'Rifugio Lissone', 'Brescia', 'rifugi_brescia_img/Rifugio_Lissone.jpg', 'Il Rifugio Città di Lissone situato nel comune di Saviore dell’Adamello , in Val Camonica, a 2.020 m. <br>\r\n                    Accanto al rifugio è presente un invaso artificiale che raccoglie le acque del torrente Poia, \r\n                    mentre una teleferica permette il trasporto di carichi dalla Malga Lincino al rifugio.<br>', 'https://www.google.it/maps/place/Rifugio+Citt%C3%A0+di+Lissone/@46.0832785,10.4945368,17z/data=!3m1!4b1!4m8!3m7!1s0x47824ba64d7cfab5:0xaf9f4db3a0a69ca2!5m2!4m1!1i2!8m2!3d46.0832785!4d10.4967255?hl=it&authuser=0', 'difficile'),
('R.M.M.C', 'Rifugio Mario Marinelli al Coca', 'Bergamo', 'rifugi_bergamo_img/Coca.jpg', 'Il rifugio Mario Merelli al Coca è stato intitolato all\'alpinista scomparso su queste montagne nel gennaio del 2012. \r\n                    Si trova a quota 1891 m in uno degli angoli più suggestivi e selvaggi delle Orobie: siamo vicino alla località nota come \"Conca dei Giganti\", \r\n                    dove svettano tutte le maggiori elevazioni del gruppo. Numerosi itinerari di arrampicata su roccia e lungo canaloni e couloir. \r\n                    Dal passo di Coca è possibile raggiungere il ghiacciaio del Lupo e il non distante bivacco Corti.\r\n                    Costruito nel 1919 su progetto dell\'ingegnere Luigi Albani, di proprietà del Club Alpino Italiano di Bergamo, \r\n                    venne dedicato al ricordo degli undici soci CAI morti durante la Prima Guerra. E’ posto  alla base dei giganti orobici: \r\n                    il Pizzo Coca (3050 m) e il Pizzo Redorta (3037 m), nonché alle altre cime che coronano la Val Bondione. L’ampliamento avvenuto nel 1957, \r\n                    su progetto dell\'architetto Maria Luisa Berti Angelini, ha dotato il rifugio di 60 posti letto e corrente elettrica.', 'https://www.google.it/maps/place/Rifugio+Merelli+al+Coca/@46.0539106,10.0064534,15.23z/data=!4m8!3m7!1s0x4783eae6479ababd:0xe7325dc7e2d7ddda!5m2!4m1!1i2!8m2!3d46.0547085!4d10.0098087?hl=it&authuser=0', 'difficile'),
('R.O', 'Rifugio Olmo', 'Bergamo', 'rifugi_bergamo_img/Olmo.jpg', 'Il rifugio dedicato alla memoria di Rino Olmo fu inaugurato il 29 settembre del 1991, \r\n                    in seguito alla ristrutturazione della Baita di Olone, con notevole impegno lavorativo ed economico da parte dei soci della Sezione CAI di Clusone. <br>\r\n                    E\' ubicato a 1819 metri di altezza con una posizione di tutto rispetto, dolcemente adagiato in una conca poco sotto il passo Olone. <br>\r\n                    Il Rifugio Olmo gode dell\'invidiabile vista sul dolomitico versante sud della Regina delle Orobie: la Presolana. <br>', 'https://www.google.it/maps/place/Rifugio+Rino+Olmo/@45.9481811,10.0355672,17z/data=!3m1!4b1!4m8!3m7!1s0x4783dd243fdfcd17:0x4032d024f9cb1005!5m2!4m1!1i2!8m2!3d45.9481811!4d10.0377559?hl=it&authuser=0', 'intermedi'),
('R.R', 'Rifugio Resegone', 'Bergamo', 'rifugi_bergamo_img/Resegone.jpg', 'L\'ultimo dei rifugi CAI bergamaschi è stato inaugurato il 15 settembre 2013. \r\n                    Realizzato dalla Sottosezione CAI Valle Imagna a quota 1265 m lungo il sentiero che da Brumano sale al Resegone è la sosta \r\n                    ideale per chi vorrà compiere il periplo del Resegone, salire alle creste, o vorrà semplicemente effettuare una breve escursione.<br>\r\n                    Escursioni partendo dal rifugio: <br>\r\n                    al Rifugio Azzoni (m.1860) in ore 1.30;<br>\r\n                    alla Vetta del Resegone (m.1875) in ore 1.35.<br>', 'https://www.google.it/maps/place/Rifugio+Resegone/@45.8560958,9.4869938,17z/data=!3m1!4b1!4m8!3m7!1s0x478403cdf0adb601:0x75999390dd46c6cc!5m2!4m1!1i2!8m2!3d45.8560958!4d9.4891825?hl=it&authuser=0', 'semplici'),
('R.SEV', 'Rifugio SEV - Corni di Canzo', 'Lecco_Como', 'rifugo_lecco-como_img/Rifugio_SEV-Corni_di_Canzo.jpg', 'Nella zona di Pianezzo, a fianco dei Corni di Canzo, meta abituale degli escursionisti del territorio lecchese, \r\n                    è situato il rifugio della Società Escursionisti Valmadreresi; \r\n                    iniziato nel 1957 e i cui lavori terminarono nel 1964 grazie al contributo di numerosi soci volontari. <br>', 'https://www.google.it/maps/place/Rifugio+S.E.V./@45.8642842,9.3251813,17z/data=!3m1!4b1!4m8!3m7!1s0x47841dcd0b6085a9:0x5f8740d1fed121d7!5m2!4m1!1i2!8m2!3d45.8642842!4d9.32737?hl=it&authuser=0', 'difficile'),
('R.T', 'Rifugio Tagliaferri', 'Bergamo', 'rifugi_bergamo_img/Tagliaferri.jpg', 'Il rifugio è posto quale tappa intermedia all\'itinerario naturalistico Antonio Curò trovandosi esattamente a metà strada tra il rifugio Curò e il passo del Vivione. <br>\r\n                    L\'ambiente è molto interessante sia per la fauna e la flora (la zona è tutelata dalla riserva faunistico venatoria Valbelviso – Barbellino), \r\n                    sia per i numerosi specchi d\'acqua sparsi lungo tutti i versanti delle montagne circostanti.\r\n                    Locale invernale con apparato SOS che permette di effettuare chiamate dirette al CNSAS e al 118. <br>\r\n                    Venne inaugurato il 22 settembre 1985 grazie alla volontà degli scalvini con il contributo economico della comunità  Montana e del CAI di Bergamo. \r\n                    É intitolato al primo presidente della Sottosezione Valle di Scalve, Nani Tagliaferri, tragicamente scomparso nel 1981 tra i ghiacci delle Ande Peruviane, \r\n                    insieme agli amici Italo Maj e Livio Piantoni. <br>\r\n                    L’anno seguente subì un devastante incendio che lo distrusse quasi completamente ma la tenacia dei soci permise l’immediata ricostruzione. \r\n                    Situato a 2328 m s.l.m. è il rifugio più alto delle Orobie. <br>', 'https://www.google.it/maps/place/Rifugio+Nani+Tagliaferri/@46.05537,10.1123954,17z/data=!3m1!4b1!4m8!3m7!1s0x4783c6c0d7b3ae1b:0x1368d4eb995adabd!5m2!4m1!1i2!8m2!3d46.05537!4d10.1145841?hl=it&authuser=0', 'difficile'),
('R.TO', 'Rifugio Tonolini', 'Brescia', 'rifugi_brescia_img/Rifugio_Tonolini.jpg', 'Il rifugio Franco Tonolini si trova nella Conca del Baitone, nel Parco dell Adamello, nei pressi del lago Rotondo. <br>\r\n                    Circondato da ben otto bellissimi laghetti alpini e in posizione ideale per ottime escursioni .<br>', 'https://www.google.it/maps/place/Rifugio+Franco+Tonolini/@46.1504498,10.4381329,17z/data=!3m1!4b1!4m8!3m7!1s0x4783b31ebc2d871b:0xfcdda27227754318!5m2!4m1!1i2!8m2!3d46.1504498!4d10.4403216?hl=it&authuser=0', 'semplici'),
('R.V.A', 'Rifugio Volta A.', 'Sondrio', 'rifugio_sondrio_img/Rifugio_Volta.jpg', 'Il Rifugio Volta è situato al centro della testata della Val dei Ratti.\r\n                    Gli fanno da corona le cime che separano questa valle dalla Val Codera e dalla Val Masino. <br>\r\n                    Partendo da sinistra (ovest) vediamo: il Sasso Manduino (m. 2888), \r\n                    la Punta Magnaghi (m. 2871), le Cime di Gaiazzo (m. 2597 e m. 2920), la Bocchetta di Spassato (m. 2820), \r\n                    il Pizzo Ligoncio (m. 3032), il Pizzo della Vedretta (m. 2907), la Cima del Calvo (m. 2967), il Passo di Primalpia (m. 2476),<br> \r\n                    il M. Spluga o Cima di Dosenigo (m. 2845).<br>', 'https://www.google.it/maps/place/Capanna+Volta/@46.2242886,9.5386642,17z/data=!3m1!4b1!4m5!3m4!1s0x478471d002a40cbd:0x3e58797ce7eb74c7!8m2!3d46.2242886!4d9.5408529?hl=it&authuser=0', 'intermedi');

-- --------------------------------------------------------

--
-- Table structure for table `utente`
--

CREATE TABLE `utente` (
  `IDUtente` int(5) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `nome` varchar(50) NOT NULL,
  `cognome` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `utente`
--

INSERT INTO `utente` (`IDUtente`, `email`, `password`, `nome`, `cognome`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'admin', 'admin'),
(2, 'utente', '3ce98305181b1bac59d024a49b0ffd73', 'utente', 'utente'),
(3, 'esempio', 'cd3e0a0700045ed656f1f561801b134f', 'esempio', 'esempio'),
(7, 'esempio2', '1a9a03744f7a496b5f5bb6409bb26e80', 'esempio2', 'esempio2');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recensioni`
--
ALTER TABLE `recensioni`
  ADD PRIMARY KEY (`ID_Recensione`) USING BTREE,
  ADD KEY `recensioni_ibfk_1` (`Rifugio`),
  ADD KEY `Utente_che_ha_scritto` (`Utente`);

--
-- Indexes for table `rifugi`
--
ALTER TABLE `rifugi`
  ADD PRIMARY KEY (`IDRifugio`);

--
-- Indexes for table `rifugi_tmp`
--
ALTER TABLE `rifugi_tmp`
  ADD PRIMARY KEY (`IDRifugio`);

--
-- Indexes for table `utente`
--
ALTER TABLE `utente`
  ADD PRIMARY KEY (`IDUtente`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recensioni`
--
ALTER TABLE `recensioni`
  MODIFY `ID_Recensione` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--
-- AUTO_INCREMENT for table `utente`
--
ALTER TABLE `utente`
  MODIFY `IDUtente` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `recensioni`
--
ALTER TABLE `recensioni`
  ADD CONSTRAINT `Utente_che_ha_scritto` FOREIGN KEY (`Utente`) REFERENCES `utente` (`IDUtente`),
  ADD CONSTRAINT `recensioni_ibfk_1` FOREIGN KEY (`Rifugio`) REFERENCES `rifugi` (`IDRifugio`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
